apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt-cw-test
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vm-cw-net
  namespace: kubevirt-cw-test
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "name": "vm-cw-net",
      "type": "cw-multinet",
      "mtu": 1450,
      "vxlanPort": 14789,
      "ipam": {
        "type": "whereabouts",
        "range": "10.254.50.0/24",
        "exclude": ["10.254.50.0/28"]
      }
    }
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: cwm-vm-a
  namespace: kubevirt-cw-test
  labels:
    app: cwm-vm-a
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: cwm-vm-a
    spec:
      nodeSelector:
        kubernetes.io/hostname: g46cd14
      terminationGracePeriodSeconds: 0
      domain:
        cpu:
          cores: 1
        resources:
          requests:
            memory: 256Mi
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
            - name: cwmnet
              bridge: {}
              model: virtio
      networks:
        - name: default
          pod: {}
        - name: cwmnet
          multus:
            networkName: kubevirt-cw-test/vm-cw-net
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
            networkData: |
              network:
                version: 1
                config:
                  - type: physical
                    name: eth0
                    subnets:
                      - type: dhcp
                  - type: physical
                    name: eth1
                    subnets:
                      - type: dhcp
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: cwm-vm-b
  namespace: kubevirt-cw-test
  labels:
    app: cwm-vm-b
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: cwm-vm-b
    spec:
      nodeSelector:
        kubernetes.io/hostname: g80b396
      terminationGracePeriodSeconds: 0
      domain:
        cpu:
          cores: 1
        resources:
          requests:
            memory: 256Mi
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
            - name: cwmnet
              bridge: {}
              model: virtio
      networks:
        - name: default
          pod: {}
        - name: cwmnet
          multus:
            networkName: kubevirt-cw-test/vm-cw-net
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
            networkData: |
              network:
                version: 1
                config:
                  - type: physical
                    name: eth0
                    subnets:
                      - type: dhcp
                  - type: physical
                    name: eth1
                    subnets:
                      - type: dhcp
